SSL 인증서는 나중에 필요합니다.
자체 서명된 CA 및 인증서를 사용하지 않는 경우, 시작하기 전에 다음 사항을 확인하십시오:

* 인증 기관(CA) SSL 공개 인증서입니다.
  CA 체인을 사용하는 경우 모든 중간 CA도 사용 가능해야 합니다.
* SSL 데이터베이스 개인 키.
* SSL 인증서

모든 파일은 PEM 형식이어야 합니다.

SSL 서버 인증서의 호스트 이름은 이를 배포하는 시스템의 정규화된 호스트 이름과 일치해야 합니다.
인증서의 `X509v3 Subject Alternative Name` 섹션에서 호스트 이름을 설정할 수 있습니다.
환경에 따라 여러 호스트 이름을 나열할 수도 있습니다.
지원되는 키 유형은 `RSA` 및 `EC` (타원 곡선)입니다.

[NOTE]
====
과거에는 데이터베이스 SSL 인증서는 `reportdb` 및 `db`를 `Subject Alternative Name`로 필요로 했습니다.
이제는 더 이상 필요하지 않으며, (보고서 데이터베이스에 액세스하는 데 사용되는) 서버 FQDN만을 `Subject Alternative Name`로 필요로 합니다.
====

데이터베이스 컨테이너는 외부에 노출된 완전한 도메인 이름만 필요합니다.
`db` 및 `reportdb` SAN이 포함된 이전 인증서를 계속 사용할 수 있습니다.

같은 인증서를 메인 컨테이너와 데이터베이스 컨테이너 모두에 사용할 수 있습니다.

새 인증서를 업그레이드 명령에 전달하려면 `--ssl-db-ca-root`, `--ssl-db-cert` 및 `--ssl-db-key` 매개변수를 사용하십시오.



ifeval::[{mlm-content} == true]

{productname} 5.2에서는 `uyuni-server` 및 `uyuni-db` Podman 컨테이너 간의 내부 통신이 최적화되었습니다.
이 트래픽은 엄격하게 로컬이므로, 이제 `/etc/rhn/rhn.conf`에서 TLS가 명시적으로 비활성화되었습니다. 
결과적으로, 인증서의 주체 대체 이름(SAN)에 `db` 및 `reportdb`을(를) 정의하는 것은 더 이상 필요하지 않거나 사용되지 않습니다. 
그러나 경계 보안이 더욱 엄격해졌으며, PostgreSQL 포트(`5432`)에 대한 원격 연결은 이제 `/var/lib/pgsql/data/pg_hba.conf`을(를) 통해 TLS로 보호되도록 명시적으로 강제됩니다.

endif::[]
