SSL証明書は後の段階で必要になります。
自己署名で生成されたCAおよび証明書を使用しない場合は、開始前に以下が揃っていることを確認してください。

* 証明書機関（CA）のSSL公開証明書。
  CAチェーンを使用している場合は、すべての中間CAも利用可能でなければなりません。
* SSLデータベース機密鍵。
* SSLデータベース証明書。

認証キーは常にPEM形式である必要があります。

SSLサーバー証明書のホスト名は、それをデプロイするマシンの完全修飾ホスト名に一致する必要があります。
証明書の`X509v3 Subject Alternative Name`セクションでホスト名を設定できます。
環境が必要とする場合は、複数のホスト名をリストすることもできます。
サポートされているキータイプは`RSA`および`EC`（楕円曲線）です。

[NOTE]
====
以前は、データベースSSL証明書には`reportdb`および`db`が`Subject Alternative Name`として必要でした。
これは不要となり、`Subject Alternative Name`としてサーバーFQDN（レポートデータベースへのアクセスに使用）のみが必須となります。
====

データベースコンテナには、外部に向けた完全修飾ドメイン名のみが必要です。
`db`および`reportdb`のSANを持つ古い証明書は引き続き使用できます。

同じ証明書をメインコンテナとデータベースコンテナの両方に使用できます。

新しい証明書をアップグレードコマンドに渡すには、`--ssl-db-ca-root`、`--ssl-db-cert`、および`--ssl-db-key`パラメータを使用します。



ifeval::[{mlm-content} == true]

{productname} 5.2では、`uyuni-server`と`uyuni-db`のPodmanコンテナ間の内部通信が最適化されました。
このトラフィックは厳密にローカルであるため、`/etc/rhn/rhn.conf`ではTLSが明示的に無効化されています。
その結果、証明書のサブジェクト代替名（SAN）で`db`および`reportdb`を定義することは不要となり、使用されなくなりました。
しかし、境界セキュリティが強化されたため、PostgreSQLポート（`5432`）へのリモート接続は、`/var/lib/pgsql/data/pg_hba.conf`を介してTLSで保護されることが明示的に義務付けられています。

endif::[]
