[[autoinst-owngpgkey]]
= 独自のGPGキーを使用する
:description: 自分のGPGキーを設定して、パッケージメタデータに安全に署名し、それをインストールメディアの初期RAMディスクに追加して、より安全な環境を提供します。
:revdate: 2024-07-10
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

自動インストールのために使用しているリポジトリに署名されていないメタデータがある場合は、通常、自動インストール用ディストリビューションのオプションとして[option]``+insecure=1+``カーネルパラメータを使用し、[path]+``+spacewalk/sles_no_signature_checks+``コードスニペットを{ay}インストールファイルで使用する必要があります。

より安全な代替方法は、独自のGPGキーを提供することです。

[NOTE]
====
この技術は{suse}クライアントにのみ適用されます。
====

.プロシージャ:独自のGPGキーを追加してください。
. GPGキーを作成します。
. このキーを使用して、パッケージのメタデータに署名します。
. インストールメディアの初期RAMディスクにこのキーを追加します。
. GPGキーをコンテナにコピーするには、[command]``+mgradm gpg add+``を使用します。
  このコマンドはGPGキーをコピーし、顧客のキーリングに追加します。
. コマンド[command]``+mgradm restart+``を実行します。
  このコマンドは、SUSEと顧客のキーリングを使用して、一意のキーリングを作成します。

[NOTE]
====
新しいGPGキーでメタデータに署名した場合、すでにオンボードされているクライアントは新しいキーについて知らないことになります。
理想的には、クライアントを登録する前にメタデータに署名するべきです。

リポジトリを使用するオンボード済みのクライアントの場合、修正方法は、そのクライアントでGPGキーのチェックを無効にすることです。
====
