[[client-upgrades-uyuni]]
= Uyuniクライアントのアップグレード
:description: Uyuni クライアントを構成するには、チャンネルを追加し、リポジトリを同期し、パッケージをアップグレードします。すべての変更が正常に同期されていることを確認してください。
:revdate: 2025-02-26
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメントチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1
ifeval::[{mlm-content} == true]

:noindex:
endif::[]

このセクションでは、例としてopenSUSE Leapを使用します。

== アップグレードの準備


.プロシージャ:クライアントのアップグレードの準備
. {productname} サーバのコマンドプロンプトで、root ユーザーとして、[command]``+spacewalk-common-channels+`` コマンドを実行し、適切なチャンネルを追加します。
+
----
spacewalk-common-channels \
opensuse_leap15_4 \
opensuse_leap15_4-non-oss \
opensuse_leap15_4-non-oss-updates \
opensuse_leap15_4-updates \
opensuse_leap15_4-uyuni-client
----

. [command]``+spacewalk-repo-sync+`` を使って、全てのチャンネルを完全に sync します。
+
// These are custom channels.
// For more information, see xref:client-configuration:clients-opensuse.adoc[].

. {productname} サーバ {webui} で、menu:ソフトウェア[チャンネルの管理> に移動し、][systemitem]``+Uyuni Client Tools for openSUSE Leap 15.4 (x86_64)+`` チャンネル名をクリックします。

. 右上隅の btn:[チャンネルの管理] をクリックします。

. [guimenu]``+Repositories+`` タブをクリックし、[systemitem]+``+External - Uyuni Client Tools for openSUSE Leap 15.3 (x86_64)+`` を選択します。

. btn:[リポジトリの更新] をクリックします。

. menu:リポジトリ[sync] サブタブに移動し、btn:[今すぐsync] をクリックします。

. [systemitem]``+openSUSE Leap 15.4 (x86_64)+``+ と [systemitem]+``+External - openSUSE Leap 15.3 (x86_64)+`` で同様の操作を行います。

[systemitem]``+openSUSE Leap 15.4 (x86_64)+`` を展開し、パッケージが含まれているすべての子チャンネルを表示します。



== アップグレード

クライアントをアップグレードするには、ソフトウェアリポジトリを置き換え、ソフトウェアを更新し、最後にクライアントを再起動します。



.プロシージャ:クライアントのアップグレード

. {productname} サーバ {webui} で、menu:システム[] に移動し、クライアントの名前をクリックします。
. menu:ソフトウェア[ソフトウェアチャンネル] をクリックし、ベースチャンネルとして openSUSE Leap {opensuse-version} チャンネルを選択します。これは [systemitem]``+Customs Channels+`` リストに表示されています。
. [guimenu]``+子チャンネル+`` ペインで、{opensuse-version} 子チャンネルを選択します。
. btn:[次へ] をクリックし、[guimenu]``+ソフトウェアチャンネルの変更を確認+`` を btn:[確認] します。
. menu:ソフトウェア[パッケージ> アップグレード] をクリックし、クライアントで更新するすべてのパッケージを選択してから、選択を適用します。
  btn:[パッケージのアップグレード] をクリックし、詳細を確認して、btn:[確認] をクリックして更新を完了します。
. クライアントを再起動します。

多くのクライアントを更新する必要がある場合は、{productname} サーバでこのコマンドシーケンスのアクションチェーンを作成できます。
アクションチェーンを使用して、複数のクライアントに同時に更新を行うことができます。


////
. Assign the new channels to the clients instead of the old channels.

. Update all the packages.  This can either be done with the {webui} or better run [command]``+zypper dup+`` manually on the command line local on the systems or remotely as a Salt command.
////

////
I think the better way to document this is if giving it a try. Create an Uyuni server, sync Leap 15.1 (spacewalk-common-channels), create a Leap 15.1, onboard it, sync Leap 15.2 (spacewalk-common-channels), and then try to adjust the channels and trying to upgrade. I recommend you use VMs and take snapshots of the VMs so you can repeat steps as needed.
////

////
But for now you need to create and mirror at least the target channels with spacewalk-common-channels.

You adjust the channels for the client and best is to call "zypper dup". Either from the commandline on that system or using remote command.
////
