[[client-proxy]]
= プロキシへのクライアントの登録
:description: プロキシサーバーでのクライアント登録を、Web UI登録、コマンドラインコマンド、または起動するスクリプトを含む手順を通じて構成します。クライアントを移動する
:revdate: 2024-03-05
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1


プロキシサーバーは、クライアントのブローカーおよびパッケージのキャッシュとして機能することができます。
クライアントをプロキシに登録することは、{productname}サーバーに直接登録することに似ていますが、いくつかの重要な違いがあります。

これらのセクションには、{webui}を使用してプロキシにクライアントを登録する情報、コマンドラインコマンド、または起動するスクリプトに関する情報が含まれています。
クライアントを1つの{productname}プロキシから別のプロキシまたは{productname}サーバーに移動する手順もあります。

{webui}内では、プロキシページがクライアントに関する情報を表示します。
menu:システム[システム一覧> プロキシ]のプロキシ名をクリックすることで、プロキシに接続されているクライアントの一覧を見ることができます。その後、[guimenu]+[guimenu]``+プロキシ+``+のサブタブを選択します。

menu:システム[すべて]でクライアントの名前をクリックすることで、クライアントのチェーンされたプロキシの一覧を表示し、[guimenu]+[guimenu]``+接続+``+のサブタブを選択できます。



== プロキシ間でのクライアントの移動


クライアント({salt})および{salt} SSHプッシュクライアントをプロキシ間で移動することができ、登録プロセスを繰り返す必要はありません。

[IMPORTANT]
====
チェーンされたプロキシを移動することはできません。
チェーンされたプロキシを移動する代わりに、新しいプロキシを作成し、クライアントを移動して、古いプロキシを削除します。
====



.プロシージャ:プロキシ間でクライアントまたは{salt} SSHプッシュクライアントを移動する

. {productname} {webui}で、プロキシ間で移動するクライアントのための[guimenu]``+システムの詳細+``ページに移動します。
. [guimenu]``+接続+``タブに移動します。
  次に、ドロップダウンメニューを見るために[guimenu]``+プロキシの変更+``リンクに従います。
. [guimenu]``+新しいプロキシ+``ドロップダウンメニューから、クライアントの移動先のプロキシを選択し、btn:[プロキシの変更]をクリックします。



.プロシージャ:SSMを使用してプロキシ間で複数のクライアントまたは{salt} SSHプッシュクライアントを移動する

. {productname} {webui}で、menu:システム[システム一覧]に移動し、移動する各クライアントを確認します。これにより、クライアントがシステムセットマネージャに追加されます。
. menu:システム[システムセットマネージャ]に移動し、menu:その他[プロキシ]タブに移動します。
. [guimenu]``+新しいプロキシ+``ドロップダウンメニューから、クライアントの移動先のプロキシを選択し、btn:[プロキシの変更]をクリックします。

[systemitem]``+system.changeProxy+`` API呼び出しでも同じ機能を利用できます。



=== 背景情報
この機能の効果は、通常のSaltクライアントとSalt SSH Pushクライアントで異なります。


==== デフォルトのクライアント

この機能は、{salt}状態アクションをスケジュールし、[literal]``+master:+``+設定を[path]+``+susemanager.conf+`` {salt}クライアント設定ファイル内で新しいプロキシを指すように変更します。
その後、この機能は{salt}クライアントを再起動します。

[NOTE]
====
手動で [path]+``+susemanager.conf+`` ファイルを編集して [literal]``+master:+``+ を変更しても、同じ効果があり、この方法もサポートされています。
====

クライアントが再起動して新しいプロキシ経由で再接続すると、サーバはデータベース内のプロキシパスを更新し、チャンネルURLを更新するための別のアクションをスケジュールします。



==== {salt} SSHプッシュクライアント

この機能はデータベース内のプロキシパスをただちに更新し、チャンネルURLを更新するための新しいアクションがスケジュールされます。



== プロキシからサーバへのクライアントの移動

クライアントをプロキシからサーバーに移動する場合は、プロキシリストから[literal]``+なし+``を選択します。


