[[script-client-proxy]]
= ブートストラップスクリプトを使用してクライアントをプロキシに登録する
:description: SUSE Multi-Linux Manager Serverでmgr-bootstrapコマンドラインツールを使用して作成されたブートストラップスクリプトを使い、クライアントがプロキシサーバに接続するように設定します。
:revdate: 2025-03-20
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメントチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1


クライアントは、ブートストラップスクリプトを使用して{productname}プロキシを通じて登録できます。
これは、{productname}サーバに直接クライアントを登録するのとほぼ同じ方法で行われます。

[command]``+mgr-bootstrap+``コマンドラインツールを使用して、{productname}サーバコンテナ内でブートストラップスクリプトを作成します。[command]``+mgr-bootstrap+``は、プロキシの完全修飾ドメイン名（FQDN）、アクティベーションキー、またはGPGキーなどのパラメータを必要とします。
プロキシのFQDNは必須です。
他のすべてのパラメータは、特定のセットアップに依存します。


その後、ブートストラップスクリプトは、クライアントに必要すべての情報を配備します。



.プロシージャ:ブートストラップスクリプトを使用してクライアントをプロキシに登録する

. {productname}サーバで{webui}を使用してクライアントアクティベーションキーを作成します。
  詳細については、xref:client-configuration:activation-keys.adoc[]を参照してください。
. サーバのコンテナホストで、コンテナ内で端末を起動します。

+

[source,shell]
----
mgrctl term
----

+

--
.. コンテナ内でブートストラップスクリプトを作成するには、たとえば、次のオプションを指定して[command]``+mgr-bootstrap+``コマンドを実行します。

+

[source,shell]
----
mgr-bootstrap --hostname=MLM_PROXY --activation-keys=ACTIVATION_KEY \
  --script bootstrap-MLM_PROXY.sh
----

+

[literal]``+MLM_PROXY+``をプロキシのホスト名に置き換えます。

+
[option]``+--スクリプト+``オプションを使用すると、説明的な名前でブートストラップスクリプトを保存できます。
   必要に応じて、追加のコマンドラインオプションを使用してブートストラップスクリプトをカスタマイズします。
   使用できるオプションを表示するには、コマンドラインに[command]``+mgr-bootstrap --help+``と入力します。

.. オプション:結果として得られたブートストラップスクリプトを編集します。
--

. ブートストラップスクリプトを実行します。
  次の2つのオプションがあります：

+

* スクリプトをクライアントに転送し、クライアント上で直接実行します。
  代わりに、プロキシがリクエストをサーバーに転送するため、クライアントはhttp://MLM_PROXY/pub/bootstrap-MLM_PROXY.sh.からダウンロードできます。[literal]``+MLM_PROXY+``をプロキシのホスト名に置き換えてください。

* プロキシから[command]``+ssh+``を使用してスクリプトを実行してください。
  [literal]``+MLM_PROXY+``+をプロキシのホスト名に、[systemitem]+``+ <client.example.com>+``をクライアントのホスト名にそれぞれ置き換えてください。

+

[source,shell]
----
cat /srv/www/htdocs/pub/bootstrap/bootstrap-MLM_PROXY.sh | ssh root@<client.example.com> /bin/bash
----
