[[custom-info]]
= カスタムシステム情報
:description: キーと値のペアを使用して、特定のマシンに割り当て可能なカスタマイズされたクライアント情報の含め方を学びます。
:revdate: 2024-03-05
:page-revdate: {revdate}
:page-author: SUSE製品・ソリューションドキュメントチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

カスタマイズされたシステム情報をクライアントに含めることができます。
システム情報は、クライアントに割り当てることができる[literal]``+キー:値+``のペアとして定義されます。
例えば、特定のプロセッサに対して[literal]``+キー:値のペア+``を定義し、そのプロセッサがインストールされているすべてのクライアントにそのキーを割り当てることができます。
カスタムシステム情報はカテゴリ分けされており、{productname} {webui}を使用して検索できます。

始める前に、カスタム情報を保存できるキーを作成する必要があります。



.プロシージャ:カスタムシステム情報キーの作成
. {productname} {webui}に移動し、menu:システム[カスタムシステム情報]をクリックし、btn:[キーの作成]をクリックします。
. [guimenu]``+キーラベル+``フィールドに、キーの名前を追加します。
  スペースは使用しません。
  例えば、``+intel-x86_64-quadcore+``です。
. [guimenu]``+説明+``フィールドに必要な追加情報を入力します。
. 必要な各キーで操作を繰り返します。

情報は{salt}ピラーを介して利用可能です。
次のようなコマンドでこの情報を取得できます:

----
salt $minionid pillar.get custom_info:key1
----

このコマンドは、次のような出力になります。

----
$minionid:
    val1
----

カスタムシステム情報キーを作成するとき、キーをクライアントに適用できます。



.プロシージャ:クライアントにカスタム情報キーを適用する
. {productname} {webui}に移動し、カスタム情報を適用するクライアントをクリックし、menu:詳細[カスタム情報]タブに移動します。
. btn:[値の作成]をクリックします。
. 適用する値を見つけ、キーラベルをクリックします。
. [guimenu]``+値+``フィールドに追加情報を入力します。
. btn:[キーの更新]をクリックしてカスタム情報をクライアントに適用します。

設定管理に関する詳細については、xref:client-configuration:configuration-management.adoc[]を参照してください。
