[[troubleshooting-]]
= 对容器全盘空间用尽事件进行查错
:description: 按照以下步骤调整存储介质的大小，以排查容器中的磁盘已满事件。
:revdate: 2025-03-10
:page-revdate: {revdate}
:page-author: SUSE 产品与解决方案文档团队
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1



////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

如果挂接为容器永久性存储媒体的专用磁盘的存储空间用尽，您需要采取紧急措施。

请执行以下操作，通过调整存储媒体大小来解决问题。
以 [literal]``+root+`` 用户身份在容器主机上运行所有列出的命令。

.过程：升级调整存储介质大小

. 增加磁盘大小。
  采取的措施取决于安装场景。

. 如果磁盘已分区（例如，磁盘 [path]+``+/dev/vdb+`` 有 [path]``+/dev/vdb1+``+ 分区），请运行以下命令：

+

运行以下命令：

+

--
.. [command]``+parted /dev/vdb+``
.. [literal]``+(parted)+``+ [command]+``+print+``
.. [literal]``+(parted)+``+ [command]+``+resizepart NUMBER 100%+``+ 其中 [literal]+``+NUMBER+``+ 是 [command]+``+print+``+ 命令显示的分区号（例如，如果 [literal]+``+/dev/vdb1+``，则为 [literal]+``+1+``+）
.. [literal]``+(parted)+``+ [command]+``+quit+``
--

. 调整文件系统大小。
  例如，对于 XFS 文件系统，运行以下命令：

+

[source,shell]
----
xfs_growfs /dev/vdb1
----

完成该过程后，XFS 文件系统应该会使用该磁盘上的所有可用空间。
