include::partial$variables.adoc[]
= 시그스토어 호스트 기능
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 컨테이너 이미지를 검증하고 안전한 어드미션 제어를 적용하기 위해 Kubewarden에서 CEL 정책을 사용하여 시그스토어 호스트 기능을 구현하는 방법을 알아보세요.
:doc-persona: ["kubewarden-policy-developer", "kubewarden-operator"]
:doc-topic: ["kubewarden", "writing-policies", "cel", "sigstore", "signature", "verification"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "쓰기 정책", "sigstore", "서명", "검증"]
:sidebar_label: 시그스토어 호스트 기능
:current-version: {page-origin-branch}

kubewarden의`+cel-policy+` 에서 호스트 기능의 다른 사용 예로, 시그스토어 키가 없는 서명을 확인하여 파드의 모든 컨테이너 이미지를 확인하는 정책을 만들어 보겠습니다.

== 예시: 서명 스토어 인증 정책

이 정책은 파드 시그스토어의 모든 컨테이너 이미지를 확인하고 이미지가 서명되고 신뢰할 수 있는지 확인한다.

이 경우 GitHub Actions에서 수행된 Sigstore 키 없는 서명을 확인합니다. 이러한 유형의 키 없는 서명은 암호화 인증서를 만들 때 GitHub의 OIDC 발급자와 연결되므로 컨테이너 이미지가 게시된 GitHub 조직만 알면 됩니다. 시그스토어의 호스트 기능에 대한 자세한 내용은xref:reference/spec/host-capabilities/02-signature-verifier-policies.adoc[여기에서] 확인할 수 있습니다.

CEL에서 이를 달성하기 위해 정책에서 https://github.com/kubewarden/cel-policy?tab=readme-ov-file#host-capabilities[{project-name} 의 호스트 기능을 위한 CEL 확장 라이브러리], 특히 https://pkg.go.dev/github.com/kubewarden/cel-policy/internal/cel/library#Sigstore[`+githubAction+`함수]를 사용합니다.

항상 그렇듯이 `+kwctl+` 에서 시작할 수 있습니다:

[subs="+attributes",console]
----
$ kwctl scaffold manifest -t ClusterAdmissionPolicy \
  registry://ghcr.io/kubewarden/policies/cel-policy:v1.0.0`
----

그런 다음 컨테이너 인증 정책과 관련되도록 편집할 수 있습니다:

[subs="+attributes",yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: "cel-sigstore-keyless-verification"
spec:
  module: ghcr.io/kubewarden/policies/cel-policy:v1.0.0
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations: ["CREATE", "UPDATE"]
----

이제 CEL 부분으로 넘어가 보겠습니다. 현재 파드 오브젝트에서 컨테이너 이미지 목록을 가져온 다음, 선택한 조직(이 경우, github.com/opencontainers)과 일치하는 서명으로 확인합니다:

[subs="+attributes",yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: "cel-sigstore-keyless-verification"
spec:
  module: ghcr.io/kubewarden/policies/cel-policy:v1.0.0
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations: ["CREATE", "UPDATE"]
  settings:
    variables:
      - name: containerImages
        expression: |
          object.spec.containers.map(c, c.image)
      - name: containerImagesNotVerified
        expression: |
          variables.containerImages.filter(image, !kw.sigstore.image(image).githubAction("opencontainers").verify().isTrusted())
    validations:
      - expression: |
          size(variables.containerImagesNotVerified) == 0
        messageExpression: "'These container images are not signed by the kubewarden GitHub organization: ' + variables.containerImagesNotVerified.join(', ')"
----

하지만 잠시만요, InitContainer도 파드의 일부가 될 수 있다는 것을 잊지 말아야 합니다. 이제 다른 변수와 유효성 검사를 추가해 보겠습니다:

```yaml title="./cel-policy-sigstore.yaml"
apiVersion: policies.kubewarden.io/v1
kind: 클러스터 어드미션폴리시 메타데이터: 이름: "셀-시그스토어-키리스-검증" 스펙: 모듈: ghcr.io/kubewarden/policies/cel-policy:v1.0.0 namespaceSelector: matchLabels: kubernetes.io/metadata.name: 기본 규칙:- apiGroups: [""] apiVersions: ["v1"] 리소스: ["pods"] 작업: ["CREATE", "UPDATE"] 설정: 변수: - 이름: containerImages 표현식: | object.spec.containers.map(c, c.image) - 이름: initContainerImages 표현식: | has(object.spec.initContainerImages) ? object.spec.initContainers.map(c, c.image) : [] - name: containerImagesNotVerified 표현식: | variables.containerImages.filter(image, !kw.sigstore.image(image).githubAction("opencontainers").verify().isTrusted()) - name: initContainerImagesNotVerified 표현식: | variables.initContainerImages.filter(image, !kw.sigstore.image(image).githubAction("opencontainers").verify().isTrusted()) 유효성 검사:- 표현식 | size(variables.containerImagesNotVerified) == 0 messageExpression: "'이 컨테이너 이미지는 kubewarden GitHub 조직에서 서명하지 않았습니다: ' + variables.containerImagesNotVerified.join(', ')" - 표현식: | size(variables.initContainerImagesNotVerified) == 0 messageExpression: "'이 초기화 컨테이너 이미지는 kubewarden GitHub 조직에서 서명하지 않았습니다: ' + variables.initContainerImagesNotVerified.join(', ')"
```

As usual with CEL, we can add several `+validations+` under
`+settings.validations+`, and they are evaluated in parallel, joined with an AND
operation, which is short-circuited.

We can now deploy the policy, and try to deploy a Pod with unsigned images:

```console
$ kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: golanci-lint-example
spec:
  containers:
  - name: nginx
    image: ghcr.io/opencontainers/golangci-lint:v1.52.1
    ports:
    - containerPort: 80
EOF
Error from server: error when creating "STDIN":
  admission webhook "clusterwide-cel-sigstore-keyless-verification.kubewarden.admission" denied the request:
  failed to verify image: Callback evaluation failure: no signatures found for image: ghcr.io/opencontainers/golangci-lint:v1.52.1
```
