== 准备 {sles} {bci-mlm} 主机


或者，您可以 {productname}在 {sles} {bci-mlm}上部署。

下面的过程介绍安装过程的主要步骤。


=== 在 {productname} 上安装 {sles} 扩展

.过程：升级在 {productname} 上安装 {sles} 扩展
[role=procedure]
____

. 在 找到并下载 {sles} {bci-mlm} [literal]``+.iso 映像+`` https://www.suse.com/download/sles/.。

. 确保您拥有宿主操作系统 ({sles} {bci-mlm}) 和扩展的注册代码。

. 开始安装 {sles} {bci-mlm}。

  .. 在 [literal]``+语言、键盘和产品选择+`` 中选择要安装的产品。

  .. 在 [literal]``+许可协议+`` 中，阅读协议并选中 [guimenu]+``+我同意许可条款+``。

. 选择注册方法。在本示例中，我们将使用 SUSE Customer Center 注册服务器。

. 请输入您的 {scclongform} 电子邮件地址。

. 输入您的 {sles} {bci-mlm} 注册代码。

. 单击 [systemitem]``+下一步+`` 继续。

+

[IMPORTANT]
====
请注意，对于 {sles} {bci-mlm}，您需要拥有有效的 {sles} 订阅和相应的注册代码，您必须在此屏幕上提供。
您需要在下面输入 {productname} 扩展的注册代码。
====

. 在 [literal]``+扩展和模块选择+`` 页面上，检查以下内容：

+

  * 选择 {productname} 服务器扩展以安装服务器，或选择 {productname} 代理扩展以安装代理。
  * \{sles} Basesystem 模块
  * 容器主机

. 单击 [systemitem]``+下一步+`` 继续。

. 输入您的 {productname} {productnumber} 扩展注册代码。

. 单击 btn:[下一步] 继续。

. 完成安装。

. 安装完成后，以 root 身份登录。

. 更新系统（可选，如果在安装期间未将系统设置为自动下载更新）：

+

[source,shell]
----
zypper up
----

. 重引导。

____


=== 可选：从命令行注册

如果您在 {productname} {productnumber} 安装期间将 {sles} 添加为扩展，则可以跳过此过程。

但是，您可以选择在 {sles} 安装期间通过选择 btn:[跳过注册] 按钮来跳过注册。
本节提供在 {sles} 安装后注册您的产品的步骤。

[NOTE]
====
以下步骤使用 {productname} {productnumber} 扩展与 {x86_64} 架构进行注册，因此需要 {x86_64} 架构的注册代码。

要注册 {arm} 或 {s390x} 架构，请使用正确的注册代码。
====


.过程：升级从命令行注册
[role=procedure]
____

. 可以运行以下命令来禁用计时器：

+

[source,shell]
----
SUSEConnect --list-extensions
----

+

. 可以运行以下命令来禁用计时器：

+

* 如果安装服务器，请使用您的 {productname} 服务器扩展 {productnumber} x86_64 注册代码。

+

例如，对于 {sle} 15 SP7，请使用以下命令：

+

[source,shell]
----
SUSEConnect -r <regcode>
SUSEConnect -p sle-module-containers/15.7/x86_64
SUSEConnect -p Multi-Linux-Manager-Server-SLE/5.1/x86_64 -r <regcode>
----

+

* 如果安装代理，请使用您的 {productname} 代理扩展 {productnumber} x86_64 注册代码运行以下命令：

+

----
SUSEConnect -p Multi-Linux-Manager-Proxy-SLE/5.1/x86_64 -r <regcode>
----

____



=== 安装并启用 [package]``+podman+``

.过程：升级正在安装 [package]``+podman+``
[role=procedure]
____

. 在容器主机上以 \`root` 身份登录。

+

* 重引导服务器。

+

[source,shell]
----
zypper in podman
zypper in -t product Multi-Linux-Manager-Server-SLE
----

* 在代理上：

+

[source,shell]
----
zypper in podman
zypper in -t product Multi-Linux-Manager-Proxy-SLE
----

+

[IMPORTANT]
====
确保已安装软件包 [package]``+podman+``。
此外，在服务器上 [package]``+mgradm+``+ 和 [package]+``+mgradm-bash-completion+``+ 或在代理上，[package]+``+mgrpxy+``+ 和 [package]+``+mgrpxy-bash-completion+`` 也需要安装。
====

+

. 重引导系统或运行以下命令，以启动 Podman 服务：

+

[source, shell]
----
systemctl enable --now podman.service
----

____
