= 기본 구성 재정의
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: {stackstate-product-name} 셀프 호스팅

https://github.com/StackVista/helm-charts/tree/master/stable/suse-observability[{stackstate-product-name} 헬름 차트에서] 여러 값을 설정할 수 있습니다. 예를 들어 각 구성 요소에 대해 `tolerations` 및 `nodeSelectors` 을 사용자 지정할 수 있습니다. 사용자 지정 구성을 추가하고 환경 변수를 포함할 수도 있습니다.

== 다음에 대한 사용자 지정 구성 {stackstate-product-name} `api`

{stackstate-product-name} `api` 서비스의 경우 사용자 정의 구성을 헬름 차트에 직접 드롭할 수 있습니다. 이 방법은 {stackstate-product-name} 에서 제공하는 기본 구성을 재정의하는 것이 좋으며 특히 인증을 사용자 지정하는 데 편리합니다. 이렇게 설정한 구성은 {stackstate-product-name} 구성 파일( https://github.com/lightbend/config/blob/master/HOCON.md[] HOCON 형식)에서 사용할 수 있습니다.

예를 들어 {stackstate-product-name} 로그인 페이지에 사용자 지정 '비밀번호 분실 링크'를 설정할 수 있습니다:

[tabs]
====
values.yaml::
+
--

[,text]
----
stackstate:
  components:
    api:
      config: |
        stackstate.api.authentication.forgotPasswordLink =
        "https://www.stackstate.com/forgotPassword.html"
----

--
====

[NOTE]
====
여기에서 설정한 사용자 지정 구성은 xref:/setup/install-stackstate/kubernetes_openshift/customize_config.adoc#_environment_variables[환경 변수에] 의해 재정의된다는 점에 유의하세요.
====


== 환경 변수

모든 {stackstate-product-name} 서비스(`receiver`, `k2es-*`, `correlation`, `api`)의 구성은 환경 변수를 사용하여 사용자 지정할 수 있습니다. 환경 변수는 `values.yaml` 파일에 지정되며 `secret` (비밀번호 등) 또는 `open` (일반 값)이 될 수 있습니다. 구성 항목을 환경 변수 이름으로 변환하려면 `.` 을 `_` 으로 바꾸고 접두사 `CONFIG_FORCE_` 를 추가합니다.

[,text]
----
# configuration item
stackstate.api.authentication.forgotPasswordLink

# environment variable name
CONFIG_FORCE_stackstate_api_authentication_forgotPasswordLink
----

예를 들어 {stackstate-product-name} 로그인 페이지에 사용자 지정 '비밀번호 분실 링크'를 설정할 수 있습니다:

[tabs]
====
values.yaml::
+
--

[,text]
----
stackstate:
  components:
    api:
      extraEnv:
        # The value for open env vars is defined on the deployment
        open:
          CONFIG_FORCE_stackstate_api_authentication_forgotPasswordLink: "https://www.stackstate.com/forgotPassword.html"
        # The value for secret env vars is defined in a secret and referenced from the deployment
        secret:
          CONFIG_FORCE_some_config_with_sensitive_data: "data-stored-in-secret"
----

--
====

[NOTE]
====
{stackstate-product-name} `api` 서비스의 경우 환경 변수가 <<_custom_configuration_for_suse_observability_api, `config` 을>> <<_custom_configuration_for_suse_observability_api,사용하여 설정한 사용자 지정 구성을>> 재정의합니다.
====


* 모든 다른 서비스의 이름 지정에 대한 자세한 내용은 https://github.com/StackVista/helm-charts/tree/master/stable/suse-observability[{stackstate-product-name} 헬름 차트 readme에서] 확인할 수 있습니다.
* xref:/setup/security/authentication/README.adoc[인증 사용자 지정]에 대한 자세한 내용을 알아보세요.
