[[content-staging]]
= 内容暂存
:description: 通过配置参数，如 salt.content.staging.advance 和 salt.content.staging.window，管理整个组织的内容暂存。
:revdate: 2025-01-13
:page-revdate: {revdate}
:page-author: SUSE 产品与解决方案文档团队
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1


暂存用于客户端在安装前下载软件包。
这允许软件包安装在计划时间一到就立即开始，从而减少维护窗口所需的时间。


== 启用内容暂存


您可以管理整个组织的内容暂存。
在{productname} {webui}中，导航到menu:Admin[组织]以查看可用组织的列表。
单击组织名称，并勾选 [guimenu]``+启用暂存内容+`` 复选框，以允许该组织中的客户端暂存软件包数据。

[NOTE]
====
您必须以 {productname} 管理员身份登录才能创建和管理组织。
====

您还可以在命令提示符下，通过编辑 [path]``+/etc/sysconfig/rhn/up2date+`` 并添加或编辑以下行来启用暂存：

----
stagingContent=1
stagingContentWindow=24
----


``+stagingContentWindow+`` 参数是以小时为单位的时间值，决定下载何时开始。
这是在计划的安装或更新时间之前的小时数。
在这个例子中，内容会在安装时间前 24 小时被下载。
下载的开始时间取决于系统选择的联系方法。

下次安排操作时，软件包会自动下载，但不会安装。
在计划的时间，暂存的软件包会被安装。



== 配置内容暂存

有两个参数用于配置内容暂存：

* [parameter]``+salt_content_staging_advance+`` 是内容暂存窗口打开前的提前时间，以小时计。
    它是距离安装开始的小时数，经过这段时间后即可开始下载软件包。
* [parameter]``+salt_content_staging_window+`` 是内容暂存窗口的持续时间，以小时为单位。
    这是在安装开始之前客户端必须将软件包暂存的一段时间。

例如，如果 [parameter]``+salt_content_staging_advance+``+ 设置为六小时，而 [parameter]+``+salt_content_staging_window+`` 设置为两小时，则暂存窗口在安装时间前六小时打开，并保持开启两小时。
在安装开始前剩余的四个小时内，不会下载任何软件包。

如果您为 [parameter]``+salt_content_staging_advance+``+ 和 [parameter]+``+salt_content_staging_window+`` 设置相同的值，则可以在安装开始之前下载软件包。

在 [path]``+/usr/share/rhn/config-defaults/rhn_java.conf+`` 中配置内容暂存参数。

默认值：

* [path]``+salt_content_staging_advance:8 小时+``
* [path]``+salt_content_staging_window:8 小时+``


[NOTE]
====
必须启用内容暂存才能让这些参数正常工作。
====
