include::partial$variables.adoc[]
= Sigstore 主机功能
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: 了解如何在 Kubewarden 中使用 CEL 策略实施 Sigstore 主机功能，以验证容器映像并执行安全准入控制。
:doc-persona: ["kubewarden-policy-developer", "kubewarden-operator"]
:doc-topic: ["kubewarden", "writing-policies", "cel", "sigstore", "signature", "verification"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "writing policies", "sigstore", "signature", "verification"]
:sidebar_label: Sigstore 主机功能
:current-version: {page-origin-branch}

作为 kubewarden's`+cel-policy+` 上主机功能另一种用法的示例，让我们创建一个策略，通过检查 Pod 中所有容器映像的 Sigstore 无密钥签名来验证它们。

== 例如Sigstore 验证政策

该策略将检查 Pod Sigstore 中的所有容器映像，并验证映像是否已签名和可信。

在这种情况下，我们将检查在 GitHub Actions 中执行的 Sigstore 无密钥签名。在创建加密证书时，这类无密钥签名与 GitHub 的 OIDC 签发者绑定，因此我们只需知道容器镜像发布所在的 GitHub 组织。有关 Sigstore 主机功能的更多信息，请xref:reference/spec/host-capabilities/02-signature-verifier-policies.adoc[点击此处]。

为了在 CEL 中实现这一目标，我们在策略中使用了https://github.com/kubewarden/cel-policy?tab=readme-ov-file#host-capabilities[{project-name}'用于主机能力的 CEL 扩展库]，特别是https://pkg.go.dev/github.com/kubewarden/cel-policy/internal/cel/library#Sigstore[`+githubAction+`函数]。

像往常一样，我们可以从`+kwctl+` 开始：

[subs="+attributes",console]
----
$ kwctl scaffold manifest -t ClusterAdmissionPolicy \
  registry://ghcr.io/kubewarden/policies/cel-policy:v1.0.0`
----

然后，我们就可以对其进行编辑，使其与我们的容器验证政策相关：

[subs="+attributes",yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: "cel-sigstore-keyless-verification"
spec:
  module: ghcr.io/kubewarden/policies/cel-policy:v1.0.0
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations: ["CREATE", "UPDATE"]
----

现在，让我们来看看 CEL 部分。我们将获取当前 Pod 对象中的容器映像列表，然后检查它们是否通过与我们选择的组织（在本例中为 github.com/opencontainers）相匹配的签名验证：

[subs="+attributes",yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: "cel-sigstore-keyless-verification"
spec:
  module: ghcr.io/kubewarden/policies/cel-policy:v1.0.0
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations: ["CREATE", "UPDATE"]
  settings:
    variables:
      - name: containerImages
        expression: |
          object.spec.containers.map(c, c.image)
      - name: containerImagesNotVerified
        expression: |
          variables.containerImages.filter(image, !kw.sigstore.image(image).githubAction("opencontainers").verify().isTrusted())
    validations:
      - expression: |
          size(variables.containerImagesNotVerified) == 0
        messageExpression: "'These container images are not signed by the kubewarden GitHub organization: ' + variables.containerImagesNotVerified.join(', ')"
----

但是等等，我们不能忘记 InitContainers 也可以是 Pod 的一部分。因此，让我们再添加一个变量和验证：

```yaml title="./cel-policy-sigstore.yaml"
apiVersion: policies.kubewarden.io/v1
kind:ClusterAdmissionPolicy metadata: name: "cel-sigstore-keyless-verification" spec: module: ghcr.io/kubewarden/policies/cel-policy:v1.0.0 namespaceSelector: matchLabels: kubernetes.io/metadata.name: default rules：- apiGroups: [""] apiVersions：[资源：["pods"] 操作：[设置： 变量： - name: containerImages expression：| object.spec.containers.map(c, c.image) - name: initContainerImages expression：| has(object.spec.initContainerImages) ? object.spec.initContainers.map(c, c.image) : [] - name: containerImagesNotVerified expression：| variables.containerImages.filter(image, !kw.sigstore.image(image).githubAction("opencontainers").verify().isTrusted()) - name: initContainerImagesNotVerified expression：| variables.initContainerImages.filter(image, !kw.sigstore.image(image).githubAction("opencontainers").verify().isTrusted()) validations：- expression：| size(variables.containerImagesNotVerified) == 0 messageExpression: "'这些容器图像未经 kubewarden GitHub 组织签名：'+ variables.containerImagesNotVerified.join(', ')" - expression：| size(variables.initContainerImagesNotVerified) == 0 messageExpression: "'这些初始容器图像未经 kubewarden GitHub 组织签名：'+ variables.initContainerImagesNotVerified.join(', ')" - expression: "这些初始容器图像未经 kubewarden GitHub 组织签名：'+ variables.initContainerImagesNotVerified.join(', ')"
```

As usual with CEL, we can add several `+validations+` under
`+settings.validations+`, and they are evaluated in parallel, joined with an AND
operation, which is short-circuited.

We can now deploy the policy, and try to deploy a Pod with unsigned images:

```console
$ kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: golanci-lint-example
spec:
  containers:
  - name: nginx
    image: ghcr.io/opencontainers/golangci-lint:v1.52.1
    ports:
    - containerPort: 80
EOF
Error from server: error when creating "STDIN":
  admission webhook "clusterwide-cel-sigstore-keyless-verification.kubewarden.admission" denied the request:
  failed to verify image: Callback evaluation failure: no signatures found for image: ghcr.io/opencontainers/golangci-lint:v1.52.1
```
