[[troubleshooting-]]
= 「ディスクがいっぱいになったコンテナ」イベントのトラブルシューティング
:description: コンテナ内のディスクが満杯になった場合は、ストレージのサイズを変更するために以下の手順に従ってトラブルシュートしてください。
:revdate: 2025-03-10
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメントチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1



////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

コンテナの永続ストレージメディアとしてマウントされた専用ディスクのストレージ領域が不足した場合は、緊急アクションが必要になります。

ストレージメディアのサイズ変更に関する問題を解決するには、次の手順に従います。
コンテナホスト上で、すべてのコマンドを[literal]``+root+``として実行してください。

.プロシージャ:ストレージメディアのサイズを変更する

. ディスクサイズを増やします。
  取るべき対応はインストールシナリオによって異なります。

. ディスクがパーティション設定されている場合（たとえば、ディスク[path]+``+/dev/vdb+``に[path]``+/dev/vdb1+``がある場合）、次のコマンドを実行します：

+

次のコマンドを実行します。

+

--
.. [command]``+parted /dev/vdb+``
.. [literal]``+(parted)+``+ [command]+``+print+``
.. [literal]``+(parted)+``+ [command]+``+resizepart NUMBER 100%+``+ ここで、[literal]+``+NUMBER+``+は[command]+``+print+``+コマンドによって表示されるパーティション番号です（たとえば、[literal]+``+1+``+の場合、[literal]+``+/dev/vdb1+``）
.. [literal]``+(parted)+``+ [command]+``+quit+``
--

. ファイルシステムのサイズを変更してください。
  たとえば、XFSファイルシステムの場合、次のコマンドを実行してください：

+

[source,shell]
----
xfs_growfs /dev/vdb1
----

手順を完了すると、XFSファイルシステムがディスク上の使用可能な容量をすべて使用しているはずです。
