[[troubleshooting-high-sync-times-over-wan]]
= {productname}サーバとプロキシ間で高いsync時間のトラブルシューティング
:description: SUSE Multi-Linux Managerサーバとプロキシ間のsync時間が長い場合のトラブルシューティングのために、ネットワークトラフィックを分析し、syncを調整します。
:revdate: 2025-02-06
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure.

.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////




WebUIまたはAPIコールを介して配布またはシステム設定に対して実行される変更に応じて、[command]``+cobbler sync+``コマンドが{productname}サーバから{productname}プロキシシステムにファイルを転送するために必要になる場合があります。
これを達成するために、{cobbler}は[literal]``+/etc/cobbler/settings+``に指定されたプロキシのリストを使用します。

その設計上、[command]``+cobbler sync+``は変更されたファイルや最近追加されたファイルのみをsyncすることはできません。

代わりに、[command]``+cobbler sync+``+を実行すると、[literal]+``+/srv/tftpboot+``+ディレクトリの完全なsyncが、[literal]+``+/etc/cobbler/settings+``に設定されたすべてのプロキシに対してトリガーされます。
また、関与するシステム間のWAN接続のレイテンシにも影響されます。

syncのプロセスが完了するまでにかなりの時間がかかる場合があります。これは[literal]``+/var/log/cobbler/+``のログによるものです。

たとえば、次の日時に開始したとします。

----
Thu Jun  3 14:47:35 2021 - DEBUG | running python triggers from /var/lib/cobbler/triggers/task/sync/pre/*
Thu Jun  3 14:47:35 2021 - DEBUG | running shell triggers from /var/lib/cobbler/triggers/task/sync/pre/*
----

そして、次の日時に終了したとします。

----
Thu Jun  3 15:18:49 2021 - DEBUG | running shell triggers from /var/lib/cobbler/triggers/task/sync/post/*
Thu Jun  3 15:18:49 2021 - DEBUG | shell triggers finished successfully
----

転送量は約1.8 GBでした。
転送にはほぼ30分かかりました。

比較すると、[literal]``+/srv/tftboot+``と同じサイズの大きな単一ファイルのコピーは、数分以内に完了します。


//== Resolution and analysis

[literal]``+rsync+``-ベースのアプローチに切り替えて、{productname}サーバとプロキシ間でファイルをコピーすることで、転送時間と待機時間を短縮できる場合があります。

このタスクを達成するためのスクリプトは、https://suse.my.salesforce.com/sfc/p/1i000000gLOd/a/1i000000ll5B/B2AmvIJN2_JsAyjTQzCVP_x5ioVgd0bYN9X9NpMugS8.からダウンロード可能です。

スクリプトはコマンドラインオプションを受け付けません。
スクリプトを実行する前に、手動で編集し、[literal]``+MLMHOSTNAME+``、[literal]+``+MLMIP+``+、および[literal]+``+MLMPROXY1+``変数を正しく設定する必要があります。

[WARNING]
====
スクリプトの個別調整に対するサポートはありません。
スクリプトとその内部のコメントは、プロセスと考慮すべきステップの概要を提供することを目的としています。
さらなる支援が必要な場合は、SUSEコンサルティングに連絡してください。
====


スクリプトを使用した提案されるアプローチは、次の環境で役立ちます。

* {productname}プロキシシステムがWAN接続を介して接続されています。
* [literal]``+/srv/tftboot+``には、ディストリビューション用ファイルおよびクライアントPXEブートファイルが多数含まれており、合計で数千ファイルがあります。
* [literal]``+/etc/cobbler/settings+``の任意のプロキシは無効になっており、それ以外の場合、{productname}は引き続きプロキシとコンテンツをsyncします。
+
----
#proxies:
# - "MLMproxy.MLMproxy.test"
# - "MLMproxy2.MLMproxy.test"
----


.プロシージャ:新しいsync速度の分析

. {productname}と関連するシステム間のTCPトラフィックのダンプを取得します。
* {productname}サーバー上：
+
----
tcpdump -i ethX -s 200 host <ip-address-of-susemanagerproxy> and not ssh
----
+
* {productname}プロキシ上：
+
----
tcpdump -i ethX -s 200 host <ip-address-of-susemanager> and not ssh
----
+
* これにより、分析を実行するのに十分な200のパッケージサイズのみがキャプチャされます。
* プロキシと通信するために{productname}が使用するネットワークインタフェースに対して、ethXを調整してください。
* 最後に、さらにパッケージ数を削減するため、ssh通信はキャプチャされません。
. [command]``+cobbler sync+``を開始します。
* syncを強制するため、最初に{cobbler}のjsonキャッシュファイルを削除してから、[command]``+cobbler sync+``を実行します。
+
----
rm /var/lib/cobbler/pxe_cache.json
cobbler sync
----
+
. {command]``+cobbler sync+``が終了したら、TCPdumpを停止します。
. Wiresharkを使用してTCPダンプを開き、[guimenu]``+Statistics > Conversations+``に移動して、ダンプが分析されるのを待ちます。
. TCPタブに切り替えます。
  このタブに表示される数値は、{productname}サーバーと{productname}プロキシ間でキャプチャされた会話の総数を示します。
. 列[guimenu]``+Duration+``を探します。
* 昇順にソートして開始し、ファイルの転送にかかった最小時間を確認します。
* 降順にソートして続行し、カーネルやinitrdの転送など、大きなファイルの最大値を確認します。
+
[NOTE]
====
ポート4505と4506はSalt通信に使用されるため無視してください。
====


//=== Conclusion 

TCPdumpの分析では、{productname}サーバーからプロキシへの、サイズが約1800バイトの小さなファイルの転送に約0.3秒かかったことが示されています。

大きなファイルは多くありませんでしたが、小さなファイルの数が多いため、転送されるファイルごとに新しいTCP接続が作成され、確立された接続数が多くなりました。

したがって、最小転送時間と必要な接続数（例として約5000）がわかれば、転送時間全体の概算推定時間が得られます。5000 * 0.3 / 60 = 25分。

