= 서비스 토큰
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE 관찰 가능성

== 개요

서비스 토큰을 사용하면 사용자 계정이 없어도 SUSE Observability에 인증할 수 있습니다. 이는 CI 서버와 같은 헤드리스 서비스에서 SUSE Observability를 사용하려는 경우에 유용합니다. 이러한 시나리오에서는 일반적으로 ID 공급업체에서 사용자 계정을 프로비저닝하고 싶지 않을 것입니다.

== 서비스 토큰 관리

서비스 토큰은 xref:/setup/cli/cli-sts.adoc[`sts` CLI를] 통해 관리할 수 있습니다. 다음 명령을 사용할 수 있습니다:

[,sh]
----
> sts service-token --help
Manage service tokens.

Usage:
  sts service-token [command]

Available Commands:
  create      Create a service token
  delete      Delete a service token
  list        List service tokens

Use "sts service-token [command] --help" for more information about a command.
----

{stackstate-product-name} 을 설치할 때 <<_set_up_a_bootstrap_service_token,부트스트랩 서비스 토큰을 설정할>> 수도 있습니다.

=== 서비스 토큰 생성

[NOTE]
====
오픈 텔레메트리와 Kubernetes 스택팩을 사용하면 모든 필수 권한이 설정된 주제와 서비스 토큰을 생성할 수 있습니다.
====

{stackstate-product-name} 에 대한 서비스 토큰을 만들려면 `sts` CLI를 사용하면 됩니다.

[,sh]
----
sts service-token create
----

[NOTE]
====
서비스 토큰은 한 번만 표시된다는 점에 유의하세요. 토큰을 다시 볼 수 없습니다.
====


이 명령은 다음과 같은 명령줄 인수를 사용합니다:

|===
| 깃발 | 설명

| `--name`
| 서비스 토큰의 이름

| `--expiration`
| 서비스 토큰의 만료일 형식은 yyyy-MM-dd입니다. 만료는 선택 사항입니다.

| `--roles`
| 서비스 토큰에 할당할 역할을 쉼표로 구분한 목록입니다.
|===

예를 들어, 아래 명령은 이름 `my-service-token` 및 역할 `stackstate-k8s-troubleshooter` 을 가진 서비스 토큰을 생성합니다:

[,sh]
----
> sts service-token create --name my-service-token --roles stackstate-k8s-troubleshooter
✅ Service token created: svctok-aaaaa-bbbb-ccccc-ddddd
----

=== 부트스트랩 서비스 토큰 설정

{stackstate-product-name} 을 설치할 때 (임시) 서비스 토큰을 사용하여 부트스트랩할 수 있습니다. 이렇게 하면 {stackstate-product-name} 와 먼저 상호 작용하고 UI에서 API 토큰을 얻지 않고도 CLI를 사용할 수 있습니다. 이를 설정하려면 {stackstate-product-name} 구성 파일에 다음 스니펫을 추가하세요:

쿠버네티스에서 부트스트랩 서비스 토큰을 생성하도록 {stackstate-product-name} 을 구성하려면 `authentication.yaml` 파일에 다음 값을 추가해야 한다. 예를 들어

[,yaml]
----
stackstate:
  authentication:
    serviceToken:
      bootstrap:
        token: <token>
        roles:
          - stackstate-admin
        ttl: 24h
----

아래 단계에 따라 {stackstate-product-name} 을 구성하여 부트스트랩 서비스 토큰을 생성합니다:

. `authentication.yaml` - 부트스트랩 토큰을 추가합니다:
 ** *토큰* - {stackstate-product-name} 의 (초기) 시작 시 생성되는 토큰입니다.
 ** *역할* - 부트스트랩 토큰에 할당되는 역할의 배열입니다.
 ** *ttl* - 선택 사항입니다. 서비스 토큰의 유효 기간(기간 문자열로 표시)입니다.
. {stackstate-product-name} 설치 지침의 `values.yaml` 파일과 함께 `authentication.yaml` 파일을 저장합니다.
. 헬름 업그레이드를 실행하여 변경 사항을 적용하세요.
+
[,text]
----
 helm upgrade \
   --install \
   --namespace suse-observability \
   --values values.yaml \
   --values authentication.yaml \
 suse-observability \
 suse-observability/suse-observability
----

[NOTE]
====
* 헬름 업그레이드 명령을 처음 실행하면 파드가 다시 시작되어 가용성이 잠시 중단될 수 있다.
* 모든 `helm upgrade` 실행에 `authentication.yaml` 을 포함하세요.
* 인증 구성은 쿠버네티스 시크릿으로 저장됩니다.
====


==== 외부 시크릿에서 부트스트랩 서비스 토큰 설정하기

헬름 값을 통해 부트스트랩 토큰을 지정하는 대신 헬름 차트 외부에서 생성 및 관리되는 시크릿(외부 시크릿)에서 부트스트랩 토큰을 읽을 수도 있다. 외부에서 부스트랩 토큰을 사용하려면 다음 xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[단계에] 따라 다음 데이터를 추가하세요:

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  bootstrap_token: <base64 of token>
----

이 토큰은 이미 있는 데이터 옆의 비밀에 추가할 수 있습니다.

=== 서비스 토큰 목록

생성된 모든 서비스 토큰의 ID, 이름, 만료일 및 역할은 `sts` CLI를 사용하여 확인할 수 있습니다. 예를 들어

[,sh]
----
> sts service-token list
ID              | NAME             | EXPIRATION | ROLES
107484341630693 | my-service-token |            | [stackstate-admin]
----

=== 서비스 토큰 삭제

서비스 토큰은 `sts` CLI를 사용하여 삭제할 수 있습니다. 서비스 토큰의 ID를 인수로 전달합니다. 예를 들어

[,sh]
----
> sts service-token delete 107484341630693
✅ Service token deleted: 107484341630693
----

== 서비스 토큰 사용

SUSE Observability API를 사용할 때 서비스 토큰을 사용하여 인증합니다:* CLI를 사용할 때 * HTTP API를 직접 사용할 때 * 텔레메트리 데이터를 수집할 때

=== SUSE 관찰 가능성 `sts` CLI

서비스 토큰은 `sts` CLI를 통한 인증에 사용됩니다. 자세한 내용은 xref:/setup/cli/cli-sts.adoc#_authentication[CLI 설명서를] 참조하세요.

=== SUSE Observability API

서비스 토큰을 사용하여 SUSE Observability API와 직접 통신하려면 다음 방법 중 하나를 사용하여 요청 헤더에 추가하세요:

* `Authorization` 헤더에 입력합니다:
+
[,sh]
----
  > curl -X GET -H "Authorization: ApiKey <TOKEN>" http://localhost:8080/api/server/status
----

* `X-API-Key` 헤더에 입력합니다:
+
[,sh]
----
  > curl -X GET -H "X-API-Key: <TOKEN>" http://localhost:8080/api/server/status
----

=== 텔레메트리 데이터 수집

텔레메트리 데이터 수집을 위한 서비스 토큰을 만들려면 먼저 역할을 만들어야 합니다:
[,sh]
----
> sts rbac create-subject --subject my-agent
✅ Created subject 'my-agent'
> sts rbac grant --subject my-agent --permission update-metrics
✅ Granted permission 'update-metrics' on 'system' to subject 'my-agent'
PERMISSION   | RESOURCE
update-metrics | system
----

서비스 토큰을 사용하여 쿠버네티스 RBAC 데이터를 수집하려면 `update-scoped-permissions` 도 부여해야 한다:
[,sh]
----
> sts rbac grant --subject my-agent --permission update-scoped-permissions --resource my-cluster
✅ Granted permission 'update-scoped-permissions' on 'my-cluster' to subject 'my-agent'
PERMISSION                | RESOURCE
update-metrics            | system
update-scoped-permissions | my-cluster
----

이렇게 하면 SUSE Observability에 `my-agent` 이라는 새 역할이 생성되고 `update-metrics` 권한이 부여됩니다. 그런 다음 이 역할에 대한 서비스 토큰을 만들 수 있습니다:

[,sh]
----
> sts service-token create --name my-agent --roles my-agent
✅ Service token created: svctok-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
----

새로 생성된 서비스 토큰은 다음에서 원격 측정 데이터 인증을 위한 API 키로 사용할 수 있습니다:

* {stackstate-product-name} xref:k8s-suse-rancher-prime.adoc#_installing_the_suse_observability_agent[에이전트(RBAC 에이전트 포함)]
* xref:setup/otel/getting-started/getting-started-k8s.adoc[OTel 수집기]


