== {sles} {bci-mlm} ホストの準備


また、{productname}を{sles} {bci-mlm}にデプロイすることもできます。

次のプロシージャでは、インストールプロセスの主なステップについて説明します。


=== {productname}拡張機能を{sles}にインストールします。

.プロシージャ:{productname}拡張機能を{sles}にインストールしています。
[role=procedure]
____

. https://www.suse.com/download/sles/.で{sles} {bci-mlm} [literal]``+.iso+``を見つけてダウンロードします。

. ホストオペレーティングシステム({sles} {bci-mlm})と拡張機能の両方の登録コードがあることを確認します。

. {sles} {bci-mlm}のインストールを開始します。

  .. [literal]``+言語、キーボードおよび製品の選択+``で、インストールする製品を選択します。

  .. [literal]``+ライセンス契約+``で契約を読み、[guimenu]+``+ライセンス条項に同意します+``にチェックを付けます。

. 登録方法を選択します。この例では、SUSEカスタマーセンターにサーバーを登録します。

. {scclongform}の電子メールアドレスを入力してください。

. {sles} {bci-mlm}の登録コードを入力します。

. 継続するには[systemitem]``+次へ+``をクリックしてください。

+

[IMPORTANT]
====
{sles} {bci-mlm}については、有効な{sles}サブスクリプションと対応する登録コードが必要であり、この画面で提供する必要があります。
以下に{productname}拡張機能の登録コードを入力する必要があります。
====

. [literal]``+拡張とモジュールの選択+``の画面で、以下にチェックを付けます。

+

  * サーバをインストールするには{productname}サーバ拡張機能を選択し、プロキシをインストールするには{productname}プロキシ拡張機能を選択します。
  * ベースシステムモジュール
  * Containersモジュール

. 継続するには[systemitem]``+次へ+``をクリックしてください。

. {productname} {productnumber}拡張機能の登録コードを入力します。

. 継続するにはbtn:[次へ]をクリックしてください。

. インストールを完了します。

. インストールが完了したら、rootとして新しくインストールしたサーバにログインします。

. システムを更新します(オプション。インストール時にシステムが更新をダウンロードするように設定されていない場合)。

+

[source,shell]
----
zypper up
----

. 再起動します。

____


=== オプション:コマンドラインからの登録

{sles}のインストール中に{productname} {productnumber}を拡張機能として追加した場合は、この手順をスキップできます。

ただし、オプションとして、{sles}のインストール中にbtn:[登録をスキップ]ボタンを選択することで登録をスキップできます。
このセクションでは、{sles}のインストール後に製品を登録する手順を提供します。

[NOTE]
====
次の手順では、{x86_64}アーキテクチャを使用して{productname} {productnumber}拡張機能を登録するため、{x86_64}アーキテクチャの登録コードが必要です。

{arm}または{s390x}アーキテクチャを登録するには、正しい登録コードを使用してください。
====


.プロシージャ:コマンドラインからの登録
[role=procedure]
____

. 次のコマンドで利用可能な拡張機能を一覧表示します。

+

[source,shell]
----
SUSEConnect --list-extensions
----

+

. 利用可能な拡張機能のリストから、インストールしたい拡張機能を選択します。

+

* サーバーをインストールする場合は、{productname}サーバ拡張機能 {productnumber} x86_64の登録コードを使用してください。

+

例えば、{sle} 15 SP7の場合、次のコマンドを使用します:

+

[source,shell]
----
SUSEConnect -r <regcode>
SUSEConnect -p sle-module-containers/15.7/x86_64
SUSEConnect -p Multi-Linux-Manager-Server-SLE/5.1/x86_64 -r <regcode>
----

+

* プロキシをインストールする場合は、次のコマンドで{productname} プロキシ拡張機能 {productnumber} x86_64の登録コードを使用します。

+

----
SUSEConnect -p Multi-Linux-Manager-Proxy-SLE/5.1/x86_64 -r <regcode>
----

____



=== [package]``+podman+``をインストールおよび有効にします。

.プロシージャ:[package]``+podman+``のインストール
[role=procedure]
____

. rootとしてログインし、製品パッケージをインストールします。

+

* サーバ上:

+

[source,shell]
----
zypper in podman
zypper in -t product Multi-Linux-Manager-Server-SLE
----

* プロキシ上:

+

[source,shell]
----
zypper in podman
zypper in -t product Multi-Linux-Manager-Proxy-SLE
----

+

[IMPORTANT]
====
パッケージ[package]``+podman+``がインストールされていることを確認してください。
さらに、サーバーでは[package]``+mgradm+``+および[package]+``+mgradm-bash-completion+``+、またはプロキシでは[package]+``+mgrpxy+``+および[package]+``+mgrpxy-bash-completion+``もインストールする必要があります。
====

+

. システムを再起動するか、次のコマンドを実行してPodmanサービスを起動します。

+

[source, shell]
----
systemctl enable --now podman.service
----

____
