[[ptfs]]
= {productname}におけるPTFの使用
:description: SUSE Multi-Linux Managerの詳細な手順とステップバイステップの指示を使用して、プログラム一時修正（PTF）を構成およびデプロイします。
:revdate: 2024-11-29
:page-revdate: {revdate}
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1


SUSEは、現在サポートされているすべてのソリューションに対して、一時的な修正を顧客に直接提供しています。
これらのPTF（プログラム一時修正）は、{productname}で同期できるリポジトリとして利用可能です。


== PTFパッケージについて


PTFパッケージはプロキシパッケージを介してインストールされ、`+ptf-xxxxxx+`という名前が付けられます。ここで、xxxxxxはパッケージのバージョンではなく、パッケージ名の一部である番号です。

これらは、ソフトウェアに修正が含まれていることがわかっている正しいバージョンのパッケージに依存します。
このタイプのパッケージ：

* 誤ってインストールすることはできません(つまり、zypper更新はインストールを推奨しません)。
* 誤って削除することはできません(つまり、ユーザがzypperコマンドラインで明示的に指定しない限り、新しいパッケージバージョンはPTFバージョンに置き換わりません)。
* PTFによって以前に解決された特定の問題に新しいバージョンが対処することがわかっている場合にのみ更新されます。
* システムにすでにインストールされているパッケージのみを更新します(つまり、ソフトウェアが複数のパッケージに分割されている場合、PTFは現在システムにインストールされているパッケージのみを置き換えます)。

サポートケース調査の過程で、パッケージの正しいIDと、影響を受けるサービスの配備/再起動方法についての指示がSUSEサポートによって提供されます。


== PTFパッケージのインストール

[NOTE]
====
PTFパッケージは現在、SLE 12およびSLE 15ベースのシステムのみでサポートされています。
他のバージョンやオペレーティングシステムにはこの機能がなく、それらのページは表示されません。
====

[IMPORTANT]
====
{productname}を介してPTFチャンネルにアクセスするには、L3サポートから要求する必要があります。
====

.プロシージャ:コマンドラインを使用してPTFリポジトリを有効にし、同期する

. コンソールで[command]``+mgr-sync refresh+``と入力します。
. [command]``+mgr-sync list channel+``と入力し、あなたの{scc}アカウント名で始まり、名前に+`ptfs`+を含むチャンネルを探します。
  たとえば、`+a123456-sles-15.3-ptfs-x86_64+`と指定します。
. [command]``+mgr-sync add channel <label>+``を使用してPTFチャンネルを有効にします。

このチャンネルは現在使用可能になり、同じベースチャンネルを使用しているすべてのシステムに追加できます。

PTFパッケージは明示的にインストールする必要があります。システムを更新する際に自動的に取得されることはありません。
SUSEカスタマーサポートは、特定の問題を修正するためのPTF番号を提供します。
その番号を使用して、PTFリスト内でプロキシパッケージを特定できます。
{productname} {webui}では、インストール可能なPTFが利用可能なすべてのシステムに、それらをリストするページがあります。


.プロシージャ:{productname} {webui}を介してPTFリポジトリを有効化および同期します。

. {productname} {webui}で、menu:管理[セットアップウィザード> 製品]に移動し、PTFリポジトリを有効にする製品を探します。
. 製品の同期ステータスの横にあるbtn:[製品のチャンネルを表示]をクリックします。
. 製品の必須チャンネルとオプションチャンネルを一覧表示したポップアップが表示されます。
. オプションのチャンネルリストで、{scc}アカウント名で始まり、`+ptfs+`を含むチャンネルを探します。
  例 `+a123456-sles-15.3-ptfs-x86_64+`。
. チャンネル名の横にあるチェックボックスを使用してチャンネルを選択し、btn:[確認]をクリックして同期をスケジュールします。

オプションチャンネルを追加できるようにするには、製品をインストールする必要があることに注意してください。


.プロシージャ:PTFパッケージのインストール

. {productname} {webui}で、menu:システム[システム一覧]に移動し、PTFをインストールしたいクライアントを選択します。
. menu:システム[ソフトウェア> パッケージ> ソフトウェアチャンネル]に移動し、[systemitem]``+PTFチャンネル+``を選択します。
. btn:[次へ]をクリックし、[guimenu]``+ソフトウェアチャンネルの変更を確認+``をbtn:[確認]で行います。
. チャンネルの割り当てが完了しているかどうかを確認するには、menu:システム[イベント> 履歴]に移動して結果を確認します。
. menu:システム[ソフトウェア> PTFs> インストール]サブタブに移動します。
. インストールするPTFパッケージを選択します。
. btn:[PTFのインストール]をクリックし、[guimenu]``+プログラム一時修正（PTF）のインストールを確認+``をbtn:[確認]で行います。
. PTFのインストール結果を確認するには、menu:システム[イベント> 履歴]に移動します。


APIを使用してPTFをインストールする必要がある場合、通常の[systemitem]``+system.schedulePackageInstall+`` APIをプロキシパッケージ名とともに使用できます。


== PTFのインストール後

PTFを確認して報告された問題に対処すると、更新されたパッケージは、通常のメンテナンス更新として更新リポジトリで広く配布される前に、今後のメンテナンス更新に含める対象として追跡されます。

この修正を含む定期的な更新がリリースされると、PTFの更新版もアカウント固有のPTFリポジトリにリリースされます。
更新されたPTFは厳密な依存関係を削除し、再び更新をインストールできるようにします。

PTFの修正を含む保守更新の置き換えは、標準のパッケージ更新またはパッチのインストールによって自動的に行われます。



== パッチ適用済みバージョンのパッケージの削除

PTFをアンインストールする必要があり、パッチが適用されていないバージョンのパッケージをシステムにインストールする必要がある場合、単純なパッケージ削除は使用できません。
PTFパッケージは、標準パッケージリストページでは選択できません。


.プロシージャ:PTFパッケージの削除

. {productname} {webui}で、menu:システム[システム一覧]に移動し、PTFを削除したいクライアントを選択します。
. menu:システム[ソフトウェア> PTFs> 一覧表示/削除]サブタブに移動します。
. 削除するPTFパッケージを選択します。
. btn:[PTFsの削除]をクリックし、[guimenu]``+PTFs削除の確認+``ページでbtn:[確認]をクリックします。
. 結果を確認するには、menu:システム[イベント> 履歴]に移動します。


[NOTE]
====
PTFsを削除するには、クライアントシステムに特別なバージョンの[literal]``+libzypp+``+と[literal]+``+zypper+``をインストールする必要があります。
[command]``+zypper --help+``+を確認して、[command]+``+removeptf+``がサポートされているかどうかを確認してください。
``+一覧表示/削除+``タブは、この条件が満たされている場合にのみ表示されます。
====

APIを使用してPTFを削除する必要がある場合は、通常の[systemitem]``+system.schedulePackageRemove+`` APIをプロキシパッケージ名とともに使用できます。


== クライアント上のパッチ適用済みバージョンのパッケージを削除する

クライアント上でコンソールを使用してPTFを直接削除する必要がある場合は、特別なコマンド``+zypper removeptf+``を使用する必要があります。
他のすべての方法は、エラーを引き起こすか、重要なパッケージをシステムから削除してシステムを使用不能にするなどの望ましくない動作を引き起こす可能性があります。
