[[support]]
= サポート
:description: サポートサブタブに移動し、サービスリクエスト番号とアップロードリージョンを入力し、ターゲットシステムのデータ収集をスケジュールします。
:page-author: SUSE製品およびソリューションドキュメンテーションチーム
:page-image: https://www.suse.com/assets/img/suse-white-logo-green.svg
:page-product-name: SUSE Multi-Linux Manager
:page-product-version: 5.1

{productname}でシステムを管理する際に、{suse}からサポートを受ける権利がある場合、[command]``+supportconfig+``+や[command]+``+sosreport+``のようなサポートデータを取得できます。
管理されたクライアントからデータを取得し、それを直接SUSEグローバルテクニカルサポートにアップロードします。

== サービスリクエスト番号の作成

グローバルテクニカルサポートにサポートデータを渡す前に、まずサービスリクエスト番号を生成する必要があります。

サービス要求を作成するには、https://scc.suse.com/support/requestsにアクセスして、画面の指示に従います。
サービス要求番号を書き留めます。

[NOTE]
====
**プライバシーポリシー**

{suse}は、システムレポートを機密データとして扱います。
{suse}のプライバシーに関する取り組みの詳細については、https://www.suse.com/company/policies/privacy/.を参照してください。
====


== {productname}から{suse}へのサポートデータを収集してアップロードします。

.プロシージャ:{productname} {webui}を使用してサポートデータを収集し、アップロードします。
[role=procedure]
____
. {productname} {webui}で、menu:システム[システム一覧> すべて]に移動し、サポートデータをケースに追加する必要があるクライアントを選択します。

. 次に、[guimenu]``+詳細+``+タブに移動し、[guimenu]+``+サポート+``サブタブを選択します。

. フィールド[literal]``+サポートケース番号+``に、上記で作成したサービスリクエスト番号を入力します。

. フィールド[literal]``+アップロードリージョン+``+で、データをアップロードするサーバに応じて、[literal]+``+EU+``+または[literal]+``+US+``オプションを選択します。

. フィールド[literal]``+コマンドライン引数+``に、ターゲットシステムからデータを収集するために使用されるツールのオプションを入力できます。
  どのツールが使用されるかは、このフィールドの下のヒントで確認できます。

. フィールド[literal]``+最も早い時刻+``で、このアクションの実行時刻を選択します。

. ボタンbtn:[スケジュール]をクリックします。
  アクションはスケジュールされ、指定した時刻に実行されます。クライアントからデータを収集し、それを直接アップロードサーバにアップロードします。
____

[NOTE]
====
サポートデータを収集可能なサポート対象製品:

- {productname} プロキシ
- {productname}ハブシナリオで周辺機器サーバとして登録されているサーバ
- すべての{sles}および{opensuse}クライアント
- SUSE Libertyおよび互換クライアント
- Ubuntuクライアント
- クライアントの再起動
====


[NOTE]
====
メインの{productname}サーバからサポートデータをアップロードするには、コンテナホストから引き続き[command]``+mgradm support config+``を使用してください。
====
