include::partial$variables.adoc[]
= シグストアのホスト機能
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Kubewarden の CEL ポリシーを使用して Sigstore ホスト機能を実装し、コンテナイメージを検証して安全なアドミッション制御を実施する方法を学びます。
:doc-persona: ["kubewarden-policy-developer", "kubewarden-operator"]
:doc-topic: ["kubewarden", "writing-policies", "cel", "sigstore", "signature", "verification"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden"、"kubernetes"、"writing policies"、"sigstore"、"signature"、"verification"]]。
:sidebar_label: シグストアのホスト機能
:current-version: {page-origin-branch}

kubewarden の`cel-policy` におけるホスト機能の別の使用例として、Sigstore キーレス署名をチェックすることで Pod 内のすべてのコンテナイメージを検証するポリシーを作成してみましょう。

== 例シグストアの検証ポリシー

このポリシーは、Pod Sigstore内のすべてのコンテナイメージをチェックし、イメージが署名され信頼されていることを確認します。

この場合は、GitHub Actionsで実行されたSigstoreキーレス署名をチェックします。この種のキーレス署名は、暗号化証明書を作成する際にGitHubのOIDC発行者と結びつけられるので、コンテナ・イメージが公開されているGitHubの組織だけを知っていればよい。シグストアのホスト機能については、xref:reference/spec/host-capabilities/02-signature-verifier-policies.adoc[こちらを]ご覧ください。

CELでこれを実現するために、ポリシーの https://github.com/kubewarden/cel-policy?tab=readme-ov-file#host-capabilities[{project-name}'s CEL extension libraries for host capabilities ]、特に https://pkg.go.dev/github.com/kubewarden/cel-policy/internal/cel/library#Sigstore[`githubAction`function ]を使用する。

いつものように、`kwctl` ：

[subs="+attributes",console]
----
$ kwctl scaffold manifest -t ClusterAdmissionPolicy \
  registry://ghcr.io/kubewarden/policies/cel-policy:v1.0.0`
----

その後、コンテナ検証ポリシーに関連するように編集することができる：

[subs="+attributes",yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: "cel-sigstore-keyless-verification"
spec:
  module: ghcr.io/kubewarden/policies/cel-policy:v1.0.0
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations: ["CREATE", "UPDATE"]
----

さて、CELの部分だ。現在のPodオブジェクト内のコンテナ・イメージのリストを取得し、選択した組織（この場合はgithub.com/opencontainers）に一致する署名によって検証されていることを確認します：

[subs="+attributes",yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: "cel-sigstore-keyless-verification"
spec:
  module: ghcr.io/kubewarden/policies/cel-policy:v1.0.0
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations: ["CREATE", "UPDATE"]
  settings:
    variables:
      - name: containerImages
        expression: |
          object.spec.containers.map(c, c.image)
      - name: containerImagesNotVerified
        expression: |
          variables.containerImages.filter(image, !kw.sigstore.image(image).githubAction("opencontainers").verify().isTrusted())
    validations:
      - expression: |
          size(variables.containerImagesNotVerified) == 0
        messageExpression: "'These container images are not signed by the kubewarden GitHub organization: ' + variables.containerImagesNotVerified.join(', ')"
----

しかし、InitContainersもPodの一部であることを忘れてはならない。では、別の変数とバリデーションを追加してみよう：

```yaml title="./cel-policy-sigstore.yaml"
apiVersion: policies.kubewarden.io/v1
kind:ClusterAdmissionPolicy metadata: name: "cel-sigstore-keyless-verification" spec: module: ghcr.io/kubewarden/policies/cel-policy:v1.0.0 namespaceSelector: matchLabels: kubernetes.io/metadata.name: default rules：- apiGroups: [""] apiVersions：["v1"] resources：[ポッド"] オペレーション：[変数： - name: containerImages expression：name: containerImages expression: | object.spec.containers.map(c, c.image) - name: initContainerImages expression: | has(object.spec.initContainerImages)：name: initContainerImages expression: | has(object.spec.initContainerImages) ? object.spec.initContainers.map(c, c.image) : [] - name: containerImagesNotVerified expression: | variables.containerImages.map(c, c.image) : [] - name: initContainerImages expression: | has(object.spec.initContainerImages) ?name: containerImagesNotVerified expression: | variables.containerImages.filter(image, !kw.sigstore.image(image).githubAction("opencontainers").verify().isTrusted()) - name: initContainerImagesNotVerified expression：| 変数.initContainerImages.filter(image, !kw.sigstore.image(image).githubAction("opencontainers").verify().isTrusted()) バリデーション：- expression.Size(変数.コンテナイメージ)| size(variables.containerImagesNotVerified) == 0 messageExpression: "'These container images are not signed by the kubewarden GitHub organization: ' + variables.containerImagesNotVerified.join(', ')" - expression：| size(variables.initContainerImagesNotVerified) == 0 messageExpression: "'これらの init コンテナイメージは kubewarden GitHub 組織によって署名されていません: ' + variables.initContainerImagesNotVerified.join(', ')" - expression: "'これらの init コンテナイメージは kubewarden GitHub 組織によって署名されていません: ' + variables.initContainerImagesNotVerified.join(', ')"
```

As usual with CEL, we can add several `validations` under
`settings.validations`, and they are evaluated in parallel, joined with an AND
operation, which is short-circuited.

We can now deploy the policy, and try to deploy a Pod with unsigned images:

```console
$ kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: golanci-lint-example
spec:
  containers:
  - name: nginx
    image: ghcr.io/opencontainers/golangci-lint:v1.52.1
    ports:
    - containerPort: 80
EOF
Error from server: error when creating "STDIN":
  admission webhook "clusterwide-cel-sigstore-keyless-verification.kubewarden.admission" denied the request:
  failed to verify image: Callback evaluation failure: no signatures found for image: ghcr.io/opencontainers/golangci-lint:v1.52.1
```
